language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod
  - wget sonar.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
  - unzip sonar.zip
  - sonar-scanner.bat -D"sonar.projectKey=carolynrehm_angular-test" -D"sonar.organization=carolynrehm-github" -D"sonar.sources=." -D"sonar.host.url=https://sonarcloud.io" -D"sonar.login=SONAR_TOKEN" -D"sonar.sources=src" -D"sonar.exclusions=**/node_modules/**,**/*.spec.ts"
