language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

addons:
  sonarcloud:
    organization: carolynrehm-github
    token:
      secure: SONAR_TOKEN
script:
  - sonar-scanner