language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod
  - sonar-scanner.bat -D"sonar.projectKey=carolynrehm_angular-test" -D"sonar.organization=carolynrehm-github" -D"sonar.sources=." -D"sonar.host.url=https://sonarcloud.io" -D"sonar.login=970a60895014d1d121ec7abc57209fde4ace633d"


addons:
  sonarcloud:
    organization: carolynrehm-github
    token:
      secure: SONAR_TOKEN
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner